### ISSUE TITLE
Installation instructions: using the script does not require Blocks Code

### ISSUE THREAD

**Issue by anthonyalfimov** [dupontgu/roli-blocks-melodic-bounce#1]
With ROLI Dashboard, it is no longer required to use Blocks Code to run custom Littlefoot scripts on a Lightpad Block. This allows for simpler installation instructions:

1. Make sure you have [ROLI Dashboard](https://roli.com/products/software/blocks-dashboard) installed.
2. Copy the downloaded `<script_name>.littlefoot` file (and `<script_name>.littlefootModes` folder when applicable) into `Documents/ROLI/LittleFoot/` (both Win and MacOS; you may have to create the folders if they don't exist).
3. Launch ROLI Dashboard and select the script to load it into your Lightpad Block and tweak its parameters ("Edit" button).

**Comment by Tolsi** [comment]
Oh, I didn't know that there was the outdated method. I thought this app
might be interesting to someone.

сб, 1 июн. 2019 г., 22:06 Anthony Alfimov <notifications@github.com>:

**Comment by anthonyalfimov** [comment]
The script is interesting and fun, and updating to simpler installation instruction will help make it more accessible

**Comment by dupontgu** [comment]
@anthonyalfimov I will carve out some time to update this soon! Thanks for the notification.

**Comment by dupontgu** [comment]
I've updated the instructions!  Turns out there's an even simpler way: `File` -> `Open` within the Dashboard.  Thanks again for the heads-up

**Comment by anthonyalfimov** [comment]
Great find, I didn't know about this! The one downside of this method is that Dashboard will only install the `.littlefoot` script itself, but not the modes for it (if there are any).
